# This is a basic workflow to help you get started with Actions

name: DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
          run:
            shell: bash
#            working-directory: ./www

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Main step pushing to Outwards website :)
      - name: FTP Deploy to OVH
            uses: SamKirkland/FTP-Deploy-Action@3.1.1
            with:
              ftp-server: ftp.cluster021.hosting.ovh.net
              ftp-username: ${{ secrets.OUTWARDS_LOGIN_FTP }}
              ftp-password: ${{ secrets.OUTWARDS_FTP_PASSWORD }}
              local-dir: ./


